### ISSUE TITLE
Add new track feature: angle

### ISSUE THREAD

**Issue by imagejan** [tinevez/TrackMate-TrackAnalysis#4]
Hi @tinevez,

I was looking for a track feature measuring the directionality/angle of an entire track (i.e. the line between start and end; or alternatively some weighted mean of the single edge angles??).

I couldn't find anything like that, but I think this repository here would be suitable to hold such a track feature.

Are you accepting pull requests here, or should I rather implement this in my own add-on (i.e. it would end up in https://github.com/fmi-faim/fmi-trackmate-addons/)?

If there's some more suitable place for contributions like this, e.g. in Mastodon, I'm all ears 😉

**Comment by tinevez** [comment]
Yes I would totally put it there. Because this artifacts also ships many track features such as persistence etc...
However if you want control over releases, having your own artifact and putting it on TrackMate webpage is also ok.

**Comment by tinevez** [comment]
Yes I would totally put it there. Because this artifacts also ships many track features such as persistence etc...
However if you want control over releases, having your own artifact and putting it on TrackMate webpage is also ok.
